### ISSUE TITLE
Source for the dataset

### ISSUE THREAD

**Issue by xiaohk** [Foroughp/Manipulating-and-Measuring-Model-Interpretability#1]
Hello, I enjoy reading your paper "Manipulating and Measuring Model Interpretability"! Thank you so much for making the code and data available. I am wondering what is the source for the NYC apartment price dataset? Is it from a Kaggle challenge?

**Comment by Foroughp** [comment]
Thanks for reaching out. The source of NYC apartment prices is StreetEasy (https://streeteasy.com/), which is the most commonly used Real Estate website in NYC.

**Comment by xiaohk** [comment]
Got it, thank you!
